### ISSUE TITLE
Ability to create Account

### ISSUE THREAD

**Issue by dbard16** [drinkingChai/grace-shopper#26]
Be able to create an account, so that I can perform activities like leaving reviews, save a cart, look at previous orders, etc.

**Comment by drinkingChai** [comment]
API:
- [NEW] users.js file
  - `POST /api/users` creates a user and returns `202`
- [UPDATE] index.js to include users.js

Store:
*Thunk:*
- [NEW] registerUser
  - posts new user data to `/api/users`

Component:
- [UPDATE] UserAuth
  - add `name` to state
  - add 'registerUserHandler' class method
  - add name input field and Register button

**Comment by drinkingChai** [comment]
Complete.
