### ISSUE TITLE
Boilerplate

### ISSUE THREAD

**Issue by drinkingChai** [drinkingChai/grace-shopper#29]

**Comment by mrkit** [comment]
Once we decide on a file structure, we'll have to update three files:
server.js // database sync
webpack.config.js // the entry location, output filename
package.json // the --ignore folders

**Comment by drinkingChai** [comment]
Laid out some files and folders

app/
- index.js
- store.js `//single reducer for now`
- components/
  - Root.js

db/
- conn.js
- index.js
- seed.js `//kept separate so we can run npm run seed`

server/
- api/ `//for api routes`
index.js

package.json will do `nodemon server`
manually calling `webpack` from node_modules directory can be ignored

**Comment by drinkingChai** [comment]
Reviewed by Burcu and Dan.
