### ISSUE TITLE
MVP Wireframe - AllProducts

### ISSUE THREAD

**Issue by drinkingChai** [drinkingChai/grace-shopper#35]

**Comment by drinkingChai** [comment]
![IMG_5833.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d4280f35cca30012cb59f5/125516c66e82c728ace21e0d46c1b9bd1cd7dbfadcabf301b44fff9e2c4533317346f67274d1b12dee1428045a5a4dfa41585d41f8fc8928f2e32e6c981e5ab38532022d8c6853beb2901eb80bbb258b4887b0bb8a49c5e83520f5c6.jpg)

**Comment by burieberry** [comment]
![Screen Shot 2017-10-09 at 12.40.50 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d42e4e538de90012e39f87/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236454fa6b7191a379ed0c2f51415a4ebc30254d58eeb9cb74fce36f34985619e8d8395b76933c17afed871abc57ba20894a81b3bc891895fa2137a5dad11b61435c52dcbd4f3fb29b4bc259f34be64857a0133e64e174336e0a.png)
